apiVersion: apps/v1
kind: Deployment
metadata:
  name: tv
  labels:
    app: tv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tv
  template:
    metadata:
      labels:
        app: tv
    spec:
      containers:
      - name: tv
        image: gcr.io/mechmania2017/tv:latest
        ports:
        - containerPort: 5900
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 3.6
            nvidia.com/gpu: 1
          requests:
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: tv-service
spec:
  type: LoadBalancer
  selector:
    app: tv
  ports:
  - port: 5900
    name: tv-service
    targetPort: 5900
    protocol: TCP